
rest_calls:
  - path: /fauxapi/v1/?action=config_patch
    method: POST
    headers:
      Content-type: application/json
      fauxapi-auth: '{{ fauxapi_auth }}'
    payload: '{{ pfsense_new_config }}'
    response_format: json
    recoverable_codes: [400]
    response_expectation:
      - ['message', 'ok']
